### ISSUE TITLE
我无法下载，下载到19M就完全不动了QAQ

### ISSUE THREAD

**Issue by AoiMatsu** [wsndshx/LocalizeEpub#1]

**Comment by MeowSalty** [comment]
(沉思)~~那你可能需要换一个梯子~~ 要不重新下载一下? 

主要我自己也有一点嫌弃我写的这个wwww, 所以没有扔到网盘之类的地方. ~~虽然目前有在用C#重写一个更好一些的, 但优先级不高~~
